"""extraction status y extracted_at

Revision ID: 29e030435542
Revises: a21e4a69c7a0
Create Date: 2026-09-02 07:01:52.586539
"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '29e030435542'
down_revision: str | None = 'a21e4a69c7a0'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('article', sa.Column('extracted_at', sa.DateTime(timezone=True), nullable=True))
    op.alter_column('article', 'extraction_status',
               existing_type=sa.VARCHAR(length=24),
               type_=sa.Enum('ok', 'no_title', 'http_error', 'failed', 'robots_denied', name='extraction_status', native_enum=False, length=16),
               existing_nullable=True)
    op.create_index(op.f('ix_article_extraction_status'), 'article', ['extraction_status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_article_extraction_status'), table_name='article')
    op.alter_column('article', 'extraction_status',
               existing_type=sa.Enum('ok', 'no_title', 'http_error', 'failed', 'robots_denied', name='extraction_status', native_enum=False, length=16),
               type_=sa.VARCHAR(length=24),
               existing_nullable=True)
    op.drop_column('article', 'extracted_at')
    # ### end Alembic commands ###
