"""title_source en article

Revision ID: a21e4a69c7a0
Revises: 5c7a077ee1b3
Create Date: 2026-09-02 06:42:26.509913
"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = 'a21e4a69c7a0'
down_revision: str | None = '5c7a077ee1b3'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('article', sa.Column('title_source', sa.Enum('sitemap', 'slug', 'extracted', name='title_source', native_enum=False, length=12), nullable=True))
    op.create_index(op.f('ix_article_title_source'), 'article', ['title_source'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_article_title_source'), table_name='article')
    op.drop_column('article', 'title_source')
    # ### end Alembic commands ###
