"""esquema inicial del corpus

Revision ID: be442265c01f
Revises: 
Create Date: 2026-09-01 15:27:18.278109
"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = 'be442265c01f'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('government',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('president', sa.String(length=160), nullable=False),
    sa.Column('term', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('source_note', sa.Text(), nullable=True),
    sa.CheckConstraint('end_date > start_date', name='ck_government_dates'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('source',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('source_type', sa.String(length=32), nullable=False),
    sa.Column('country', sa.String(length=2), nullable=False),
    sa.Column('language', sa.String(length=8), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('archive_from', sa.Date(), nullable=True),
    sa.Column('reliable_from', sa.Date(), nullable=True),
    sa.Column('discovery_config', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('topic',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('parent_id', sa.String(length=64), nullable=True),
    sa.Column('keywords', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['topic.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_topic_parent_id'), 'topic', ['parent_id'], unique=False)
    op.create_table('archive_density',
    sa.Column('source_id', sa.String(length=64), nullable=False),
    sa.Column('provider', sa.String(length=32), nullable=False),
    sa.Column('period_start', sa.Date(), nullable=False),
    sa.Column('n_urls_offered', sa.Integer(), nullable=False),
    sa.Column('n_articles_stored', sa.Integer(), nullable=False),
    sa.Column('measured_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['source_id'], ['source.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('source_id', 'provider', 'period_start')
    )
    op.create_table('article',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('url_hash', sa.String(length=64), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('url_normalized', sa.Text(), nullable=False),
    sa.Column('canonical_url', sa.Text(), nullable=True),
    sa.Column('source_id', sa.String(length=64), nullable=False),
    sa.Column('government_id', sa.String(length=64), nullable=True),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('subtitle', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('author', sa.Text(), nullable=True),
    sa.Column('section', sa.String(length=160), nullable=True),
    sa.Column('image_url', sa.Text(), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('published_date', sa.Date(), nullable=True),
    sa.Column('language', sa.String(length=8), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('content_hash', sa.String(length=64), nullable=True),
    sa.Column('extraction_status', sa.String(length=24), nullable=True),
    sa.Column('http_status', sa.Integer(), nullable=True),
    sa.Column('first_seen_provider', sa.String(length=32), nullable=False),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['government_id'], ['government.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['source_id'], ['source.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('url_hash')
    )
    op.create_index(op.f('ix_article_content_hash'), 'article', ['content_hash'], unique=False)
    op.create_index('ix_article_corpus_slice', 'article', ['source_id', 'government_id', 'published_date'], unique=False)
    op.create_index(op.f('ix_article_government_id'), 'article', ['government_id'], unique=False)
    op.create_index(op.f('ix_article_published_at'), 'article', ['published_at'], unique=False)
    op.create_index(op.f('ix_article_published_date'), 'article', ['published_date'], unique=False)
    op.create_index('ix_article_source_date', 'article', ['source_id', 'published_date'], unique=False)
    op.create_index(op.f('ix_article_source_id'), 'article', ['source_id'], unique=False)
    op.create_table('collection_chunk',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('source_id', sa.String(length=64), nullable=False),
    sa.Column('provider', sa.String(length=32), nullable=False),
    sa.Column('period_start', sa.Date(), nullable=False),
    sa.Column('period_end', sa.Date(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'RUNNING', 'COMPLETED', 'FAILED', 'PARTIAL', name='chunk_status', native_enum=False, length=16), nullable=False),
    sa.Column('request_url', sa.Text(), nullable=True),
    sa.Column('n_found', sa.Integer(), nullable=False),
    sa.Column('n_new', sa.Integer(), nullable=False),
    sa.Column('n_duplicates', sa.Integer(), nullable=False),
    sa.Column('n_rejected', sa.Integer(), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('period_end > period_start', name='ck_chunk_period'),
    sa.ForeignKeyConstraint(['source_id'], ['source.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_id', 'provider', 'period_start', name='uq_chunk_identity')
    )
    op.create_index('ix_chunk_resume', 'collection_chunk', ['status', 'provider', 'source_id'], unique=False)
    op.create_index(op.f('ix_collection_chunk_status'), 'collection_chunk', ['status'], unique=False)
    op.create_table('source_domain',
    sa.Column('domain', sa.String(length=255), nullable=False),
    sa.Column('source_id', sa.String(length=64), nullable=False),
    sa.Column('is_canonical', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['source_id'], ['source.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('domain')
    )
    op.create_index(op.f('ix_source_domain_source_id'), 'source_domain', ['source_id'], unique=False)
    op.create_table('article_topic',
    sa.Column('article_id', sa.Integer(), nullable=False),
    sa.Column('topic_id', sa.String(length=64), nullable=False),
    sa.Column('matched_on', sa.String(length=32), nullable=False),
    sa.Column('matched_keyword', sa.String(length=160), nullable=True),
    sa.Column('rule_version', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['article_id'], ['article.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['topic_id'], ['topic.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('article_id', 'topic_id')
    )
    op.create_table('discovery_record',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('chunk_id', sa.Integer(), nullable=False),
    sa.Column('provider', sa.String(length=32), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('url_normalized', sa.Text(), nullable=False),
    sa.Column('url_hash', sa.String(length=64), nullable=False),
    sa.Column('title_raw', sa.Text(), nullable=True),
    sa.Column('published_at_raw', sa.String(length=64), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('article_id', sa.Integer(), nullable=True),
    sa.Column('rejected_reason', sa.Enum('OUT_OF_WINDOW', 'NOT_AN_ARTICLE', 'UNKNOWN_DOMAIN', 'MALFORMED_URL', 'DUPLICATE', name='rejection_reason', native_enum=False, length=24), nullable=True),
    sa.Column('raw_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('discovered_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['article_id'], ['article.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['chunk_id'], ['collection_chunk.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('chunk_id', 'url_hash', name='uq_discovery_per_chunk')
    )
    op.create_index(op.f('ix_discovery_record_article_id'), 'discovery_record', ['article_id'], unique=False)
    op.create_index(op.f('ix_discovery_record_chunk_id'), 'discovery_record', ['chunk_id'], unique=False)
    op.create_index(op.f('ix_discovery_record_provider'), 'discovery_record', ['provider'], unique=False)
    op.create_index(op.f('ix_discovery_record_url_hash'), 'discovery_record', ['url_hash'], unique=False)
    op.create_index('ix_discovery_unresolved', 'discovery_record', ['chunk_id', 'article_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_discovery_unresolved', table_name='discovery_record')
    op.drop_index(op.f('ix_discovery_record_url_hash'), table_name='discovery_record')
    op.drop_index(op.f('ix_discovery_record_provider'), table_name='discovery_record')
    op.drop_index(op.f('ix_discovery_record_chunk_id'), table_name='discovery_record')
    op.drop_index(op.f('ix_discovery_record_article_id'), table_name='discovery_record')
    op.drop_table('discovery_record')
    op.drop_table('article_topic')
    op.drop_index(op.f('ix_source_domain_source_id'), table_name='source_domain')
    op.drop_table('source_domain')
    op.drop_index(op.f('ix_collection_chunk_status'), table_name='collection_chunk')
    op.drop_index('ix_chunk_resume', table_name='collection_chunk')
    op.drop_table('collection_chunk')
    op.drop_index(op.f('ix_article_source_id'), table_name='article')
    op.drop_index('ix_article_source_date', table_name='article')
    op.drop_index(op.f('ix_article_published_date'), table_name='article')
    op.drop_index(op.f('ix_article_published_at'), table_name='article')
    op.drop_index(op.f('ix_article_government_id'), table_name='article')
    op.drop_index('ix_article_corpus_slice', table_name='article')
    op.drop_index(op.f('ix_article_content_hash'), table_name='article')
    op.drop_table('article')
    op.drop_table('archive_density')
    op.drop_index(op.f('ix_topic_parent_id'), table_name='topic')
    op.drop_table('topic')
    op.drop_table('source')
    op.drop_table('government')
    # ### end Alembic commands ###
